# Generated by Django 2.2.5 on 2021-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='task',
            name='comlete',
            field=models.BooleanField(default=False),
        ),
    ]
