# Generated by Django 2.2.5 on 2021-07-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0004_auto_20210719_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comlete', models.BooleanField(default=False)),
            ],
        ),
    ]
